import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Sidebar from "@/components/sidebar";
import Pagewrapper from "@/components/pagewrapper";
import { cn } from "@/lib/utils";
import SidebarNew from "@/components/sidebar-new";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen w-full bg-white text-black flex",
          inter.className,
          {
            "debug-screens": process.env.NODE_ENV === "development",
          }
        )}
      >
        {/* <Sidebar /> */}
        <SidebarNew />
        <Header />
        <Pagewrapper>{children}</Pagewrapper>
      </body>
    </html>
  );
}
